-   id: bibtex-tidy
    name: bibtex-tidy
    description: ''
    entry: bibtex-tidy
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["bibtex-tidy@1.12.0"]
    minimum_pre_commit_version: '0'
