name: main
on:
  push:
    branches: [main]
  schedule:
  - cron: '15 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: uvx --from pre-commit-mirror-maker pre-commit-mirror . --language=node --package-name=bibtex-tidy --types=bib
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/main --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
